version: 1643276206136
language: cn
aomori_widgets:
  - toc
  - category
  - tag
  - recent_posts
  - archive

# aomori_customized settings
aomori_logo: /images/code.png
aomori_logo_typed_animated: true
aomori_menu:
  Home: /
  About: /about
  Archives: /archives
aomori_widgets:
  - toc # Article navigation
  - category  # Article classification
  - tag # Article tags
  - recent_posts  # latest articles
  - archive # Article Archive
aomori_copyright: false
aomori_social:
  -
    icon: github # Boxicons name
    type: logo # Boxicons type
    url: https://github.com/zeqas
  -
    icon: linkedin-square
    type: logo
    url: https://www.linkedin.com/in/casper-shiu-564a60101/
  -
    icon: medium
    type: logo
    url: https://9c7a8956.medium.com/
aomori_google_analytics: 'UA-XXXXXXXXX-X'
aomori_favicon: 📓